// mother-frontend/micro-apps/calendar/src/ui/features/wrapper/wrapper.vue
<template>
  <!-- <UIFrame class="CalendarWrapper" :title="translation.title"> -->
    <MonthSwitcher />
    <YearSwitcher />
    <Days />
  <!-- </UIFrame> -->
</template>

<script setup lang="ts">
  // import UIFrame from '@windows98/app/Bundles/UI/UIFrameBundle/Components/UIFrame.vue'
  import Days from '../days/days.vue'
  import YearSwitcher from '../year-switcher/year-switcher.vue'
  import MonthSwitcher from '../month-switcher/month-switcher.vue'
  // import useWrapper from './use-wrapper.composable'

  // const { initCalendar, translation } = useWrapper()

  // initCalendar()
</script>

<style lang="scss" scoped src="./wrapper.style.scss" />

// micro-frontends/src/mf-calendar/src/ui/modules/wrapper/wrapper.tsx
import { DSFrame } from "@windows98/design-system"
import { Days } from "../days/days"
import { MonthSwitcher } from "../month-switcher/month-switcher"
import { YearSwitcher } from "../year-switcher/year-switcher"
import { useWrapper } from "./use-wrapper.hook"
import styles from "./wrapper.module.scss"

export const Wrapper = () => {
	const { title } = useWrapper()

	return (
		<DSFrame
			className={styles.wrapper}
			id="calculator"
			title={title}
		>
			<MonthSwitcher />
			<YearSwitcher />
			<Days />
		</DSFrame>
	)
}
