// mother-frontend/micro-apps/calendar/src/ui/features/wrapper/wrapper.vue
<template>
  <Observer>
    <UIFrame class="CalendarWrapper" :title="translation.title">
      <MonthSwitcher />
      <YearSwitcher />
      <Days />
    </UIFrame>
  </Observer>
</template>

<script setup lang="ts">
  import { Observer } from 'mobx-vue-lite'
  import UIFrame from '@windows98/app/Bundles/UI/UIFrameBundle/Components/UIFrame.vue'
  import Days from '../days/days.vue'
  import YearSwitcher from '../year-switcher/year-switcher.vue'
  import MonthSwitcher from '../month-switcher/month-switcher.vue'
  import useWrapper from './use-wrapper.composable'

  const { translation } = useWrapper()
</script>

<style lang="scss" scoped src="./wrapper.style.scss" />

// micro-apps/src/ma-calendar/src/ui/modules/wrapper/wrapper.tsx
import { observer } from "mobx-react-lite"
import { DSFrame } from "@windows98/design-system"
import { useWrapper } from "./use-wrapper.hook"
import { Days } from "../days/days"
import { MonthSwitcher } from "../month-switcher/month-switcher"
import { YearSwitcher } from "../year-switcher/year-switcher"
import styles from "./wrapper.module.scss"
import { useSyncLang } from "../../hooks/use-sync-lang.hook"

export const Wrapper = observer(() => {
	const { title } = useWrapper()

	useSyncLang()

	return (
		<DSFrame
			className={styles.wrapper}
			id="calculator"
			title={title}
		>
			<MonthSwitcher />
			<YearSwitcher />
			<Days />
		</DSFrame>
	)
})
