// micro-frontends/src/mf-pulpit/src/ui/modules/pulpit-item/pulpit-item.tsx
import type { FunctionComponent } from "react"
import styles from "./pulpit-item.module.scss"
import type { PulpitItemProps } from "./pulpit-item.types"

export const PulpitItem: FunctionComponent<PulpitItemProps> = ({
	name,
	icon,
}) => {
	return (
		<div className={styles.item}>
			<img
				className={styles.icon}
				width="32"
				height="32"
				src={`/icons/applications/${icon}.png`}
				alt={name}
			/>
			<span className={styles.name}>{name}</span>
		</div>
	)
}

// src/Bundles/App/PulpitBundle/Components/PulpitItem.vue
<template>
  <div class="PulpitItem">
    <img
      class="icon"
      width="32"
      height="32"
      :src="`/icons/applications/${iconName}.png`"
      :alt="name"
    />
    <UIText class="name">{{ name }}</UIText>
  </div>
</template>

<script setup lang="ts">
  import UIText from '@Bundles/UIBundle/Components/UIText.vue'

  defineProps({
    name: {
      type: String,
      required: true,
    },
    iconName: {
      type: String,
      required: true,
    },
  })
</script>

<style lang="scss" scoped>
  @import '@Bundles/PulpitBundle/Styles/PulpitItem.styles.scss';
</style>
